export const eventsQuery = `query fetch{
    eventTypeCollection(limit:30, order: date_DESC){
    items{
        _id
        title
        date
        shortDescription
        longDescription{
            json
        }
        price
        menu{
            json
        }
        ticketsCollection(limit:6){
            items{
                _id
                title
                ticketTime
                ticketsAvailable
                price
                addonCollection(limit:5){
                    items{
                        _id
                        title
                        price
                    }
                }
                }
            }
        }
    }
}`